apiVersion: v1
kind: Service
metadata:
  name: flow-repository
  namespace: oih-dev-ns
  labels:
    app: flow-repository
spec:
  type: NodePort
  selector:
    app: flow-repository
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
