apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-hub
  namespace: oih-dev-ns
  labels:
    app: data-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-hub
  template:
    metadata:
      name: data-hub
      labels:
        app: data-hub
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: data-hub
        image: "openintegrationhub/data-hub:latest"
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: shared-secret
              key: dataHubMongourl
        - name: PORT
          value: "1234"
        - name: IAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: shared-secret
              key: iamtoken
        - name: LOG_LEVEL
          value: trace
        livenessProbe:
          httpGet:
            port: 1234
            path: /healthcheck
        readinessProbe:
          httpGet:
            port: 1234
            path: /healthcheck
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
