apiVersion: v1
kind: Service
metadata:
  name: component-repository
  namespace: oih-dev-ns
  labels:
    app: component-repository
spec:
  type: NodePort
  selector:
    app: component-repository
  ports:
  - name: "1234"
    protocol: TCP
    port: 1234
    targetPort: 1234
