apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/localVolume/
  persistentVolumeReclaimPolicy: Recycle
