apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-claim
  namespace: oih-dev-ns
  labels:
    app: mongodb
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
