apiVersion: v1
kind: ServiceAccount
metadata:
  name: component-orchestrator-account
  namespace: oih-dev-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: component-orchestrator-role
  namespace: flows
rules:
- resources:
  - deployments
  apiGroups:
  - apps
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - cronjobs
  apiGroups:
  - batch
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - configmaps
  apiGroups:
  - ""
  verbs:
  - get
  - list
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: component-orchestrator-rolebinding
  namespace: flows
roleRef:
  name: component-orchestrator-role
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: component-orchestrator-account
  namespace: oih-dev-ns
  kind: ServiceAccount
