apiVersion: v1
kind: Service
metadata:
  name: app-directory
  namespace: oih-dev-ns
  labels:
    app: app-directory
spec:
  type: NodePort
  selector:
    app: app-directory
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
