apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-volume-claim
  namespace: oih-dev-ns
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ""
