apiVersion: v1
kind: Service
metadata:
  name: secret-service
  namespace: oih-dev-ns
  labels:
    app: secret-service
spec:
  type: NodePort
  selector:
    app: secret-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
