apiVersion: v1
kind: Service
metadata:
  name: ils
  namespace: oih-dev-ns
  labels:
    app: ils
spec:
  type: NodePort
  selector:
    app: ils
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
