apiVersion: v1
kind: Service
metadata:
  name: attachment-storage-service
  namespace: oih-dev-ns
  labels:
    app: attachment-storage-service
spec:
  type: NodePort
  selector:
    app: attachment-storage-service
  ports:
  - name: "3002"
    protocol: TCP
    port: 3002
    targetPort: 3002
