apiVersion: v1
kind: Service
metadata:
  name: audit-log
  namespace: oih-dev-ns
  labels:
    app: audit-log
spec:
  type: NodePort
  selector:
    app: audit-log
  ports:
  - protocol: TCP
    port: 3007
    targetPort: 3007
