apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: oih-dev-ns
  labels:
    app: api-service
spec:
  type: ClusterIP
  selector:
    app: component-orchestrator
  ports:
  - name: "1234"
    protocol: TCP
    port: 1234
    targetPort: 1234
  sessionAffinity: None
