apiVersion: v1
kind: Service
metadata:
  name: dispatcher-service
  namespace: oih-dev-ns
  labels:
    app: dispatcher-service
spec:
  type: NodePort
  selector:
    app: dispatcher-service
  ports:
  - protocol: TCP
    port: 3013
    targetPort: 3013
