apiVersion: v1
kind: PersistentVolume
metadata:
  name: source-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: "/System/Volumes/Data/Users/james/OIH/openintegrationhub"
    server: host.docker.internal
  persistentVolumeReclaimPolicy: Retain
