apiVersion: v1
kind: Service
metadata:
  name: web-ui
  namespace: oih-dev-ns
  labels:
    app: web-ui
spec:
  type: NodePort
  selector:
    app: web-ui
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
